import { Jost, Playfair_Display } from "next/font/google";
import "./globals.css";
import ClickSpark from "../ui/click-spark/ClickSpark";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Denise Aquino",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/logo-white.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jost.variable} ${playfair.variable}`}>
        <ClickSpark
          sparkColor="#7c5c3e"
          sparkSize={12}
          sparkRadius={18}
          sparkCount={8}
          duration={500}
        >
          {children}
        </ClickSpark>
      </body>
    </html>
  );
}
